site_name: SimplexPython SDK
theme:
  name: material
  palette:
    primary: indigo

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_if_no_docstring: false
            show_root_heading: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - API Reference:
    - Client: api/client.md
    - Users Client: api/users.md