[project]
name = "simplexbot"
version = "0.1.0"
description = "A bot framework using websockets for Simplex Chat"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "websockets>=15.0.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
]
