"""
Response type definitions for the Simplex messaging system.

This module provides type definitions for all response types and
exports a unified ChatResponse type for use in API calls.
"""

from __future__ import annotations

from typing import Union

# Import all response types from their modules
from .responses.user import (
    CRActiveUser,
    CRUsersList,
    CRUserProfile,
    CRUserProfileNoChange,
    CRUserProfileUpdated,
    CRUserContactLink,
    CRUserContactLinkUpdated,
    CRUserContactLinkCreated,
    CRUserContactLinkDeleted,
    CRUserContactLinkSubscribed,
    CRUserContactLinkSubError,
    CRUserProtoServers,
)

from .responses.chat import (
    CRChatStarted,
    CRChatRunning,
    CRChatStopped,
    CRApiChats,
    CRApiChat,
    CRApiParsedMarkdown,
    CRChatCleared,
    CRContactInfo,
    CRNewChatItems,
    CRChatItemStatusUpdated,
    CRChatItemUpdated,
    CRChatItemDeleted,
    CRMsgIntegrityError,
    CRCmdOk,
    CRContactAliasUpdated,
    CRContactRequestRejected,
    CRInvitation,
    CRSentConfirmation,
    CRSentInvitation,
    CRContactUpdated,
    CRContactsMerged,
    CRContactDeleted,
    CRReceivedContactRequest,
    CRAcceptingContactRequest,
    CRContactAlreadyExists,
    CRContactRequestAlreadyAccepted,
    CRContactConnecting,
    CRContactConnected,
    CRContactAnotherClient,
    CRContactSubError,
    CRContactSubSummary,
    CRContactsDisconnected,
    CRContactsSubscribed,
    CRHostConnected,
    CRHostDisconnected,
    CRContactConnectionDeleted,
)

from .responses.group import (
    CRGroupMemberInfo,
    CRGroupEmpty,
    CRMemberSubError,
    CRMemberSubSummary,
    CRGroupSubscribed,
    CRGroupCreated,
    CRGroupMembers,
    CRUserAcceptedGroupSent,
    CRUserDeletedMember,
    CRSentGroupInvitation,
    CRLeftMemberUser,
    CRGroupDeletedUser,
    CRGroupInvitation,
    CRReceivedGroupInvitation,
    CRUserJoinedGroup,
    CRJoinedGroupMember,
    CRJoinedGroupMemberConnecting,
    CRConnectedToGroupMember,
    CRDeletedMember,
    CRDeletedMemberUser,
    CRLeftMember,
    CRGroupRemoved,
    CRGroupDeleted,
    CRGroupUpdated,
)

from .responses.file import (
    CRRcvFileAccepted,
    CRRcvFileAcceptedSndCancelled,
    CRRcvFileStart,
    CRRcvFileComplete,
    CRRcvFileCancelled,
    CRRcvFileSndCancelled,
    CRSndFileStart,
    CRSndFileComplete,
    CRSndFileCancelled,
    CRSndFileRcvCancelled,
    CRSndGroupFileCancelled,
    CRSndFileSubError,
    CRRcvFileSubError,
)

from .responses.error import CRMessageError, CRChatCmdError, CRChatError

from .responses.misc import CRPendingSubSummary

# Define the union type for all responses
ChatResponse = Union[
    # User responses
    CRActiveUser,
    CRUsersList,
    CRUserProfile,
    CRUserProfileNoChange,
    CRUserProfileUpdated,
    CRUserContactLink,
    CRUserContactLinkUpdated,
    CRUserContactLinkCreated,
    CRUserContactLinkDeleted,
    CRUserContactLinkSubscribed,
    CRUserContactLinkSubError,
    CRUserProtoServers,
    # Chat responses
    CRChatStarted,
    CRChatRunning,
    CRChatStopped,
    CRApiChats,
    CRApiChat,
    CRApiParsedMarkdown,
    CRChatCleared,
    CRContactInfo,
    CRNewChatItems,
    CRChatItemStatusUpdated,
    CRChatItemUpdated,
    CRChatItemDeleted,
    CRMsgIntegrityError,
    CRCmdOk,
    CRContactAliasUpdated,
    CRContactRequestRejected,
    CRInvitation,
    CRSentConfirmation,
    CRSentInvitation,
    CRContactUpdated,
    CRContactsMerged,
    CRContactDeleted,
    CRReceivedContactRequest,
    CRAcceptingContactRequest,
    CRContactAlreadyExists,
    CRContactRequestAlreadyAccepted,
    CRContactConnecting,
    CRContactConnected,
    CRContactAnotherClient,
    CRContactSubError,
    CRContactSubSummary,
    CRContactsDisconnected,
    CRContactsSubscribed,
    CRHostConnected,
    CRHostDisconnected,
    CRContactConnectionDeleted,
    # Group responses
    CRGroupMemberInfo,
    CRGroupEmpty,
    CRMemberSubError,
    CRMemberSubSummary,
    CRGroupSubscribed,
    CRGroupCreated,
    CRGroupMembers,
    CRUserAcceptedGroupSent,
    CRUserDeletedMember,
    CRSentGroupInvitation,
    CRLeftMemberUser,
    CRGroupDeletedUser,
    CRGroupInvitation,
    CRReceivedGroupInvitation,
    CRUserJoinedGroup,
    CRJoinedGroupMember,
    CRJoinedGroupMemberConnecting,
    CRConnectedToGroupMember,
    CRDeletedMember,
    CRDeletedMemberUser,
    CRLeftMember,
    CRGroupRemoved,
    CRGroupDeleted,
    CRGroupUpdated,
    # File responses
    CRRcvFileAccepted,
    CRRcvFileAcceptedSndCancelled,
    CRRcvFileStart,
    CRRcvFileComplete,
    CRRcvFileCancelled,
    CRRcvFileSndCancelled,
    CRSndFileStart,
    CRSndFileComplete,
    CRSndFileCancelled,
    CRSndFileRcvCancelled,
    CRSndGroupFileCancelled,
    CRSndFileSubError,
    CRRcvFileSubError,
    # Error responses
    CRMessageError,
    CRChatCmdError,
    CRChatError,
    # Misc responses
    CRPendingSubSummary,
]
